spring:
  application:
    name: movie
  datasource:
    url: jdbc:mysql://192.168.31.100:3306/movie?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    druid:
      max-active: 20
      initial-size: 5
      max-wait: 6000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      async-init: true
  redis:
    host: 192.168.31.100
    database: 0
    port: 6379
    timeout: 1000ms
server:
  port: 8080
  public-path: http://08d0-223-68-170-209.ngrok.io/api/alipayCallback
security:
  login-url: /sys/user/login
  logout-url: /sys/user/logout
  default-role-after-registration: ROLE_user
local-file:
  img-path: D:\movie_file
  avatar-path: D:\movie_file\avatar
  mall-path: D:\movie_file\mall
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: del_flag
      logic-delete-value: 1
      logic-not-delete-value: 0
#logging:
#  level:
#    com.chenzx.movie.mapper.*: debug
